### ISSUE TITLE
Fix Mobile Styling on Feed

### ISSUE THREAD

**Issue by lb-founders** [Lightning-Bounties/lb-next#11]
We've got overflow going on for the mobile version on:
- [ ] the header
- [ ] the reward amount

Add the necessary flex and media queries to allow the feed to render appropriately on mobile.

<img width="262" alt="image" src="https://github.com/user-attachments/assets/8312d3be-ccc1-4a24-9e0d-50924aa83d40">

**Comment by aliraza556** [comment]
Hi @sutt, Please assign me

**Comment by aliraza556** [comment]
Hi @sutt, could you please check if this is the best view?

![image](https://github.com/user-attachments/assets/811c3674-3e8e-404a-acfd-669efa2b69e0)

**Comment by aliraza556** [comment]
Hi @sutt, Please review it :

![image](https://github.com/user-attachments/assets/d8524b60-6976-4ac3-b5e9-629bbc311400)

Is there anything that needs to be addressed?

**Comment by aliraza556** [comment]
Hi @sutt,

If everything is good, please merge this PR: https://github.com/Lightning-Bounties/lb-next/pull/15. then i will create this issue PR, because if I submit my PR right now, I'll encounter conflicts. So, please merge the PR mentioned above as soon as possible.

Thank you!

**Comment by sutt** [comment]
@aliraza556 I've merged the PR, feel free to submit this one,  the preview looks good to me. 

And see my comments on the previous PR for PR submission best practices 👍
