### ISSUE TITLE
Ehnance Issue Page UX

### ISSUE THREAD

**Issue by super-jaba** [Lightning-Bounties/lb-next#23]
Enhance **Issue Page** by adding the following features:
- [ ] If the Issue has a Winner, display the Winner data (username, avatar)
- [ ] If the Issue is already _closed_, don't display `Claim Reward` button
- [ ] If the issue is already _closed_, indicate it
- [ ] Round the corners of **Issue Body**

> In terms of UI, feel free to implement your ideas. However, try to stay consistent with the current style

<br/>

**Earn crypto by solving this issue**
https://app.lightningbounties.com/issue/82b69545-cff3-465e-92f0-43b182c95ba0

**Comment by MuhammadUmer44** [comment]
.

**Comment by MahtabBukhari** [comment]
@sutt Could you please assign me?

**Comment by MahtabBukhari** [comment]
Hello Guys @sutt @super-jaba waiting for next bounty task ☺️

**Comment by MahtabBukhari** [comment]
Hi @sutt I am unable to withdraw the sats to Binance App via btc lightining

![image](https://github.com/user-attachments/assets/b7439a23-ea24-4752-81d5-eb492d82de8e)
