### ISSUE TITLE
Feed card onClick area layout change

### ISSUE THREAD

**Issue by sutt** [Lightning-Bounties/lb-next#3]
Currently the Feed Card element has too much area where clicking it brings you to the bounty poster's profile. Instead we want the user to get linked to the bounty detail (e.g. `/issues/abc123-fed987...`)

### Desired Output

<img width="559" alt="image" src="https://github.com/user-attachments/assets/11098eec-dd84-45f9-a62c-5413f15f33bd">

### Current Output
As can be seen, the current hitbox for clicking into the profile is too large.

<img width="553" alt="image" src="https://github.com/user-attachments/assets/12ba91e1-c81d-44f1-94e0-888ea83bc359">

### TODO
* [ ] Add appropriate div / css / flex to make this work 
* [ ] don't disrupt the visual presentation of the card

**Comment by aliraza556** [comment]
Hi @sutt, Please assign me?
