### ISSUE TITLE
[Profile - Deposit] - QR scanner should be visible only when we click on Generate button and also Generate button should be disable when we enter empty spaces in Amount input field

### ISSUE THREAD

**Issue by MahtabBukhari** [Lightning-Bounties/lb-next#32]
### Bug:

- Currently in Profile Deposit  section Empty QR scanner show 

![image](https://github.com/user-attachments/assets/5d316320-f755-408d-91b0-03487b9d3401)

- Generate button enable even we enter empty spaces in Amount input field

![image](https://github.com/user-attachments/assets/3eaa6fed-6bcd-4e21-9c14-6d87e7c8200f)

### Acceptance Criteria:

 - [ ] QR scanner section should be visible only when we click on Deposit Generate button
 - [ ] Generate button should be enable only when we enter Deposit Amount

**Comment by MahtabBukhari** [comment]
@sutt Could you please review these issues if valid then please assign me?

**Comment by aliraza556** [comment]
Hi @MahtabBukhari, Already fixed review here: https://github.com/Lightning-Bounties/lb-next/pull/25

**Comment by aliraza556** [comment]
@MahtabBukhari, See comment the @sutt  https://github.com/Lightning-Bounties/lb-next/pull/27#issuecomment-2424164657

**Comment by aliraza556** [comment]
@MahtabBukhari, the issue is fixed. Please check the staging site, but only @sutt— did not Release v1.2

**Comment by sutt** [comment]
Thank you @MahtabBukhari looks like Ali got it.
And thanks @aliraza556 for explaining.
Looks good now:
<img width="428" alt="image" src="https://github.com/user-attachments/assets/c9bec461-feb7-4e39-a889-a3e134474a34" />
