### ISSUE TITLE
Fix Dates: Profile > Payment History Card

### ISSUE THREAD

**Issue by lb-founders** [Lightning-Bounties/lb-next#9]
The dates on the payment history are coming are being displayed incorrectly. These are displayed in profile: https://app.lightningbounties.com/me

<img width="482" alt="image" src="https://github.com/user-attachments/assets/5448ee59-1334-4a0f-8ecd-3b0b202c1a89">

Please update the component: https://github.com/Lightning-Bounties/lb-next/blob/528c27499d31e6c491fda3892dbf76ea66e5c522/src/4_entities/me/ui/PaymentsCard/PaymentsCard.tsx#L29 
to deal with the data coming back `/api/history` endpoint

**Comment by aliraza556** [comment]
@lb-founders Please assign me?

**Comment by lb-founders** [comment]
@aliraza556 Assigned!

Hold off the api error one (#8) we've got delivery of that on the way.

About 6-8 more bounties coming out today as well.

**Comment by aliraza556** [comment]
Hi @sutt, could you please guide me on how to `login` locally? When I try to log in with GitHub locally, I get the error shown in the image.

![image](https://github.com/user-attachments/assets/b2f11df6-6b9b-4d9e-8043-52f1168acd71)

`.env.local`

![image](https://github.com/user-attachments/assets/4d9f87d1-c63b-442c-9f82-80113cb5e7b0)

**Comment by sutt** [comment]
@aliraza556 you're on the right track.

I've added documentation of how to do this [here](https://docs.lightningbounties.com/docs/solve-a-bounty/working-on-opensource-frontend-lb-next)

Full test backend coming soon.

Bounty Boosted, as well.

**Comment by aliraza556** [comment]
> @aliraza556 you're on the right track.
> 
> I've added documentation of how to do this [here](https://docs.lightningbounties.com/docs/solve-a-bounty/working-on-opensource-frontend-lb-next)
> 
> Full test backend coming soon.
> 
> Bounty Boosted, as well.

@sutt Thanks Man!

**Comment by aliraza556** [comment]
Hi @sutt, I'm experiencing the same issue on the Home Page: https://app.lightningbounties.com/

![image](https://github.com/user-attachments/assets/8537b4fa-5664-4e4e-8aea-748e1dcfc666)
